module.exports = [
  {
    link: "/races",
    label: "Races",
    instructions:
      "Choose 1 race. Then, choose 1 subrace from your selected race.",
    instructionsLinks: [
      {
        link: "https://sword-and-spell.com/identity-features",
        label: "Next, choose 3 identity features",
      },
    ],
    showDefaultGuide: false,
  },
  {
    link: "/backgrounds",
    label: "Backgrounds",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/core-identities",
    label: "Core Identities",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/identity-features",
    label: "Identity Features",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/feature-options",
    label: "Feature Options",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/ability-features",
    label: "Ability Features",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/armor",
    label: "Armor",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/weapons",
    label: "Weapons",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/spellcasting-charts",
    label: "Spellcasting Charts",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/spells",
    label: "Spells",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/rules",
    label: "Rules",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/summoning",
    label: "Summoning",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/animal-companions",
    label: "Animal Companions",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/shapechange-forms",
    label: "Shapechange Forms",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/leveling-chart",
    label: "Leveling Chart",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
  {
    link: "/reference-charts",
    label: "Quick Reference",
    instructions: "",
    instructionsLinks: [],
    showDefaultGuide: true,
  },
]
