module.exports = [
  {
    link: "/leveling-chart",
    label: "Leveling Chart",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/races",
    label: "Races",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/backgrounds",
    label: "Backgrounds",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/core-identities",
    label: "Core Identities",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/identity-features",
    label: "Identity Features",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/feature-options",
    label: "Feature Options",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/ability-features",
    label: "Ability Features",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/armor",
    label: "Armor",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/weapons",
    label: "Weapons",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/spellcasting-charts",
    label: "Spellcasting Charts",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/spells",
    label: "Spells",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/rules",
    label: "Rules",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/summoning",
    label: "Summoning",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/animal-companions",
    label: "Animal Companions",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/shapechange-forms",
    label: "Shapechange Forms",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
  {
    link: "/reference-charts",
    label: "Quick Reference",
    instructions: "Pick 1 if blah",
    instructionsLinks: [{ link: "https://google.com", label: "Google" }],
  },
]
